### ISSUE TITLE
can not build packages/apps/Nfc/

### ISSUE THREAD

**Issue by ryanw0602** [NXPNFCLinux/nxpnfc_android_kitkat#1]
I use mmm packages/apps/Nfc/ to build the apk
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=4.4.2
TARGET_PRODUCT=sabresd_6dq
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a-neon
TARGET_CPU_VARIANT=cortex-a9
HOST_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-3.5.0-23-generic-x86_64-with-Ubuntu-12.04-precise
HOST_BUILD_TYPE=release
BUILD_ID=1.0.0-rc3
OUT_DIR=out
============================================
No private recovery resources for TARGET_DEVICE sabresd_6dq
make: Entering directory `/work/forlinx/android_kk4.4.2_1.0.0'
make: *** No rule to make target `out/target/product/sabresd_6dq/obj/STATIC_LIBRARIES/libxml2_intermediates/export_includes', needed by `out/target/product/sabresd_6dq/obj/SHARED_LIBRARIES/libnfc_nci_jni_intermediates/import_includes'.  Stop.

how to fix it? thanks

**Comment by jgeslin** [comment]
Did you build the complete image before adding NFC support ?
Did you try to generate libxml2 (mmm external/libxml2) ?
